### ISSUE TITLE
Ghidra 10 compatibility

### ISSUE THREAD

**Issue by IvanDSM** [kylewlacy/GhidraNes#4]
Hello, are there any plans on releasing a version of the plugin for Ghidra 10? And by the way, thanks for the work on this! :D

**Comment by slinga-homebrew** [comment]
I tried compiling this extension for Ghidra 10 and it failed: 

```

FAILURE: Build failed with an exception.

* Where:
Script '/home/user/Desktop/ghidra/support/buildExtension.gradle' line: 80

* What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'archiveBaseName' for task ':buildExtension' of type org.gradle.api.tasks.bundling.Zip.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by kylewlacy** [comment]
It looks like Ghidra 10 has had a few (minor) breaking API changes. I'll try to get a release out in the next few days.

**Comment by kylewlacy** [comment]
Alright, sorry for the delay! I finally got around to pushing a new release, which can be found here:

https://github.com/kylewlacy/GhidraNes/releases/tag/v20210802-10.0.1

**Comment by VGKintsugi** [comment]
Thanks, will test it out soon.
